---
title: 'Class 10: Machine Learning Project'
author: "Jiayi Dong"
date: "2/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r}
wisCan.df<- read.csv("https://bioboot.github.io/bimm143_S18/class-material/WisconsinCancer.csv")

```


```{r}
# select column 3 to 32

wisCan.data<-as.matrix(wisCan.df[,3:32])

```

>Q. How many patients are there in the dataset?

```{r}
nrow(wisCan.df)
```

>Q. How many cancer and non-cancer patients are there?

```{r}
table(wisCan.df$diagnosis)
# sum(wisCan.df$diagnosis=="B")
```


```{r}
grep("mean",colnames(wisCan.df), value=TRUE)
```

```{r}
round(apply(wisCan.data,2,sd),2)
```
```{r}
pca <- prcomp(wisCan.data,scale=TRUE)
summary(pca)
```
```{r}
hc <- hclust(dist(wisCan.data))
hc.cut <- cutree(hc,k=3)
plot(hc)
hc
```
```{r}
pca.hc=hclust(dist(pca$x[,1:3]),method = "ward.D2")
plot(pca.hc,col=cutree(plpca.hc, k=2)
grps2<-cutree(pca.hc, k=2)
table(grps2,wisCan.df$diagnosis)
plot(pca$x[,1],pca$x[,2],col=grps2)
```
```{r}
#url <- "new_samples.csv"
url <- "https://tinyurl.com/new-samples-CSV"
new <- read.csv(url)
npc <- predict(pca, newdata=new)
npc
```

```{r}
plot(pca$x[,1],pca$x[,2],col=wisCan.df$diagnosis)
plot(npc[,1],npc[,2],col="blue")
```


